---
title: "timeseries time"
author: "Bri Baker"
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(tsibble)
library(feasts)
library(slider)

```


```{r}
toolik <- read_csv(here("data", "toolikweather.csv"))


```

```{r}
#convert to tsibble

toolik_ts <- toolik %>% 
  mutate(date = mdy(date)) %>% 
  as_tsibble(key = NULL,
             index = date)

ggplot(toolik_ts, aes(x = date, y = mean_airtemp)) +
  geom_line()
```
 use `index_by()` to aggregate ts data
 
```{r}
toolik_month <- toolik_ts %>% 
  index_by(yr_mo = ~yearmonth(.)) %>% 
  summarize(monthly_meantemp = mean(mean_airtemp, na.rm = T))

ggplot(data = toolik_month, aes(x = yr_mo, y = monthly_meantemp)) +
  geom_line() +
  facet_wrap(~month(yr_mo, label = TRUE))
```
 
 aggregate by week
 
 
```{r}
toolik_week <- toolik_ts %>% 
  index_by(weekly = ~yearweek(.)) %>% 
  summarize(weekly_airtemp = mean(mean_airtemp, na.rm = T),
            min_air = min(mean_airtemp, na.rm = T))


```
 
filtering! 

```{r}
toolik_ts %>% 
  filter_index("2000-06" ~ "2001-10")

toolik_ts %>% 
  filter_index("2000-04-10" ~ "2006-05-15")

```


## Season plot

```{r}

toolik_ts %>% 
  filter(year(date) > 2014) %>% 
  gg_season(y = mean_airtemp)


```


```{r}
toolik_month %>% 
  gg_season(y = monthly_meantemp) +
  theme_light()
```


## Seasonal Subseries

```{r}
toolik_month %>% 
  gg_subseries(y = monthly_meantemp)
```


## Moving avg

`slider`

```{r}
set.seed(2021)
test <- rnorm(n = 100, mean = 40, sd = 10)


slide(test, ~.x, .before = 2, .after = 2)

```



```{r}
roll_toolik_15 <- toolik_ts %>% 
  mutate(ma_15d = as.numeric(slide(toolik_ts$mean_airtemp,
                                   mean,
                                   .before = 7,
                                   .after = 7)))

ggplot() +
  geom_line(data = toolik_ts, aes(x = date, y = mean_airtemp), size = 0.2, color = "gray") +
  geom_line(data = roll_toolik_15, aes(x = date, y = ma_15d), color = "orange")+
  theme_minimal()

```


# create acf

```{r}
toolik_ts %>% 
  ACF(mean_airtemp) %>% 
  autoplot()


toolik_month %>% 
  ACF(monthly_meantemp) %>% 
  autoplot()


```

## Decomposition by STL

```{r}
toolik_d <- toolik_month %>% 
  model(STL(monthly_meantemp ~ season(window = Inf)))

components(toolik_d) %>% 
  autoplot()
```


